"""
Constants, as defined by the libcpuid library.
"""

NUM_REGS = 4
VENDOR_STR_MAX = 16
BRAND_STR_MAX = 64
CODENAME_STR_MAX = 64
CPU_FLAGS_MAX = 128
MAX_CPUID_LEVEL = 32
MAX_EXT_CPUID_LEVEL = 32
MAX_INTELFN4_LEVEL = 8
MAX_INTELFN11_LEVEL = 4
MAX_INTELFN12H_LEVEL = 4
MAX_INTELFN14H_LEVEL = 4
MAX_AMDFN8000001DH_LEVEL = 4
CPU_HINTS_MAX = 16
SGX_FLAGS_MAX = 14
MASK_NCPUBITS = 8
MASK_SETSIZE = (1 << (2 * MASK_NCPUBITS)) // MASK_NCPUBITS
